
export const dashboardOptions = [
  { name: "Home", path: "/" },
  { name: "Inventory", path: "/inventory" },
  { name: "Inventory - Incoming Stock", path: "/inventory/incoming-stock" },
  { name: "Inventory - Outgoing Stock", path: "/inventory/outgoing-stock" },
  { name: "Inventory - Stock Summary", path: "/inventory/stock-summary" },
  { name: "Purchases", path: "/purchases" },
  { name: "Purchases - New Purchase", path: "/purchases/new-purchase" },
  { name: "Purchases - Purchase Report", path: "/purchases/purchase-report" },
  { name: "Sales", path: "/sales" },
  { name: "Sales - Orders", path: "/sales/orders" },
  { name: "Sales - Dispatches", path: "/sales/dispatches" },
  { name: "Sales - Deliveries", path: "/sales/deliveries" },
  { name: "Sales - Partial Dispatch Requests", path: "/sales/partial-dispatch-requests" },
  { name: "Customers", path: "/customers" },
  { name: "Customers - List", path: "/customers/customer-list" },
  { name: "Customers - KYC Approvals", path: "/customers/kyc-approvals" },
  { name: "Payments", path: "/payments" },
  { name: "Payments - Reports", path: "/payments/payment-reports" },
  { name: "Payments - Approvals", path: "/payments/payment-approvals" },
  { name: "Employees", path: "/employees" },
  { name: "Employees - Create", path: "/employees/create-employee" },
  { name: "Employees - Assign Role", path: "/employees/assign-role" },
  { name: "Employees - Manage", path: "/employees/manage-employees" },
  { name: "Live Locations", path: "/location" },
  { name: "Warehouse", path: "/warehouses" },
  { name: "Warehouse - Ongoing", path: "/warehouses/ongoing" },
  { name: "Products", path: "/products" },
  { name: "Products - Add", path: "/products/add" },
  { name: "Products - Modify", path: "/products/modify" },
  { name: "Targets", path: "/targets" },
  { name: "Targets - Sales", path: "/targets/sales-target" },
  { name: "Targets - Customers", path: "/targets/customer-target" },
];

export const storeOptions = [
  { name: "Home", path: "/store" },
  { name: "Sales", path: "/store/sales" },
  { name: "Sales - Create", path: "/store/sales?mode=create" },
  { name: "Sales - Orders", path: "/store/sales?mode=orders" },
  { name: "Sales Reports", path: "/store/sales-reports" },
  { name: "Cash Deposit", path: "/store/cashdeposit" },
  { name: "Bank Receipts", path: "/store/bank-receipts" },
  { name: "Damaged Items", path: "/store/damaged" },
  { name: "Inventory", path: "/store/inventory" },
  { name: "Current Stock", path: "/store/current-stock" },
  { name: "Stock Summary", path: "/store/stock-summary" },
  { name: "Damaged Stock", path: "/store/damaged-stock" },
  { name: "Stock Transfer", path: "/store/stock-transfer" },
  { name: "Indents", path: "/store/indents" },
  { name: "Indents - All", path: "/store/indents/all" },
  { name: "Indents - Create", path: "/store/indents/create" },
  { name: "Customers", path: "/store/customers" },
  { name: "Customers - List", path: "/store/customers/list" },
  { name: "Customers - Create", path: "/store/customers/create" },
  { name: "Employees", path: "/store/employees" },
  { name: "Products", path: "/store/products" },
  { name: "Products - Manage", path: "/store/products/manage" },
  { name: "Products - Add", path: "/store/products/add" },
  { name: "Products - Bulk Update", path: "/store/products/bulk-update" },
  { name: "Discounts", path: "/store/discounts" },
  { name: "Assets", path: "/store/assets" },
  { name: "Assets - Transfer", path: "/store/assets/transfer" },
  { name: "Expenditures", path: "/store/expenditures" },
];
